language: java
jdk:
  - openjdk6
  - openjdk7
script:
  mvn clean verify -Dgpg.skip=true

install: mvn install -DskipTests=true -Dgpg.skip=true

after_success:
  mvn -e -X clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

